# Generated by Django 4.1 on 2022-09-23 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerDetailsModel",
            fields=[
                ("cus_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("cus_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=13)),
                ("address", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                ("product_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=50)),
            ],
        ),
        migrations.CreateModel(
            name="UnitModel",
            fields=[
                ("unit_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("unit", models.CharField(max_length=20)),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="api.productmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderListModel",
            fields=[
                ("order_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("order_no", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "order_date",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default=None, max_length=1000, null=True
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=50)),
                (
                    "cus_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.customerdetailsmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderDetailsModel",
            fields=[
                ("ordered_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("unit_ordered", models.CharField(max_length=20)),
                ("price_ordered", models.DecimalField(decimal_places=2, max_digits=50)),
                ("quantity_ordered", models.IntegerField()),
                (
                    "total_amount_ordered",
                    models.DecimalField(decimal_places=2, max_digits=50),
                ),
                (
                    "order_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.orderlistmodel",
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.productmodel",
                    ),
                ),
            ],
        ),
    ]
