# Generated by Django 4.1 on 2022-09-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitmodel',
            name='unit',
            field=models.CharField(default='Unit not set', max_length=20),
        ),
    ]
