# Generated by Django 4.1 on 2022-09-24 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_unitmodel_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetailsmodel",
            name="product_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.productmodel",
            ),
        ),
    ]
